# Schema for the configuration files of the Rules module.

rules.component.*:
  type: config_entity
  label: 'Rules component'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    module:
      type: string
      label: 'Module'
    description:
      type: text
      label: 'Administrative description'
    tag:
      type: string
      label: 'Tag'
    core:
      type: string
      label: 'Drupal version'
    component:
      type: rules_component

rules.reaction.*:
  type: config_entity
  label: 'Reaction rule'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    event:
      type: string
      label: 'Event'
    module:
      type: string
      label: 'Module'
    description:
      type: text
      label: 'Administrative description'
    tag:
      type: string
      label: 'Tag'
    core:
      type: string
      label: 'Drupal version'
    expression:
      type: rules_expression.[id]
      label: 'Expression configuration'

rules.settings:
  type: config_object
  label: 'Rules settings'
  mapping:
    log_errors:
      type: string
      label: 'Logging of Rules evaluation errors'
    debug_log:
      type: boolean
      label: 'Log debug information to the available loggers'
    debug:
      type: boolean
      label: 'Show debug information'
    log_level:
      type: string
      label: 'Log level'
